# Generated by Django 4.1.7 on 2023-05-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('firstname', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('adres', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('index', models.CharField(max_length=50)),
                ('delivery', models.CharField(choices=[('express', 'Express Shipping'), ('regular', 'Regular Shipping'), ('free', 'Free Shipping')], max_length=20)),
                ('credit_1', models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('googlepay', 'Google Pay'), ('shoppay', 'Shop Pay')], max_length=20)),
                ('accept', models.BooleanField(default=False)),
            ],
        ),
    ]
