# Generated by Django 4.1.7 on 2023-05-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='adres',
            field=models.TextField(),
        ),
    ]
